export const nav=[
    {
        link:"/",
        title:"发现音乐"
    },
    {
        link:"/my",
        title:"我的音乐"
    },
    {
        link:"/friends",
        title:"朋友"
    },
    {
        link:"https://music.163.com/store/product",
        title:"商城"
    },
    {
        link:"https://music.163.com/st/musician",
        title:"音乐人"
    },
    {
        link:"https://music.163.com/#/download",
        title:"下载客户端"
    },
]